import Foundation

/// A type that can generate a documentation fragment string.
///
/// Conforming types are used by the `@Doc` macro to synthesize DocC comments.
/// The `generate(respecting:)` method may ignore configuration options for
/// initial implementations; future work can use these values to wrap lines or
/// adjust detail level.
public protocol DocumentationEntry: Sendable {
    /// Generates a documentation fragment string using the provided options.
    func generate(respecting options: DocumentationConfiguration) async throws -> String
}

/// Configuration flags and parameters used when generating documentation.
///
/// This type is an `OptionSet` with a few example flags.  Additional flags
/// and associated stored properties (like `maxColumns` or `detalization`) may
/// be added later to control formatting.  Users can provide a custom
/// configuration via the `options:` parameter of `@Doc`.
@frozen
public struct DocumentationConfiguration: OptionSet, Hashable, Sendable {
    public let rawValue: UInt8
    public init(rawValue: UInt8) { self.rawValue = rawValue }

    /// Indicates that the content was generated by AI.  This flag is unused
    /// today but reserved for future integration with AI‑powered generation.
    public static let aiGenerated = DocumentationConfiguration(rawValue: 1 << 0)
    /// Allows HTML in the generated output.  Not used by the current macros.
    public static let htmlAllowed = DocumentationConfiguration(rawValue: 1 << 1)
    /// Includes metadata at the bottom of the generated documentation.
    public static let addMetadata = DocumentationConfiguration(rawValue: 1 << 2)
    /// Includes a date updated stamp in the generated documentation.
    public static let addDateUpdated = DocumentationConfiguration(rawValue: 1 << 3)
    /// Includes usage examples in the generated documentation.
    public static let addUsageExamples = DocumentationConfiguration(rawValue: 1 << 4)

    /// The default configuration used by `@Doc` if no options are provided.
    public static let `default`: Self = [.aiGenerated]

    /// Maximum column width to wrap lines.  Default: 80.
    public var maxColumns: UInt = 80
    /// Detail level for generated documentation.
    public var detalization: Detalization = .regular

    /// Levels of detail for generated documentation.
    public enum Detalization: Int, Comparable, Hashable, Sendable {
        case concise, regular, detailed
    }
}

/// A basic documentation atom representing a single textual value.
///
/// Atoms are rendered as plain text with optional indentation.  When
/// `depth` is greater than zero, each depth level produces two leading
/// spaces.  This type conforms to `ExpressibleByStringLiteral` so that
/// string literals can be passed directly to macros expecting
/// `DocumentationEntry` values.
@frozen
public struct DocumentationAtom: DocumentationEntry, ExpressibleByStringLiteral, Hashable {
    public var depth: UInt?
    public let value: String
    public init(value: String, depth: UInt? = nil) {
        self.value = value
        self.depth = depth
    }
    public init(stringLiteral value: String) {
        self.init(value: value)
    }
    public func generate(respecting options: DocumentationConfiguration) async throws -> String {
        var prefix = ""
        if let depth, depth > 0 {
            prefix = String(repeating: "  ", count: Int(depth))
        }
        return "\(prefix)\(value)"
    }
}

/// A bullet list section with an optional header.
///
/// The `items` property holds an array of nested `DocumentationEntry` values.
/// The `depth` parameter allows nested lists; each level of depth will be
/// indented by two spaces when rendering individual items.
@frozen
public struct DocumentationSectionBulletList: DocumentationEntry, Hashable {
    public var header: String?
    public var items: [DocumentationEntry]
    public var depth: UInt?
    public init(header: String? = nil, items: [DocumentationEntry] = [], depth: UInt? = nil) {
        self.header = header
        self.items = items
        self.depth = depth
    }
    public func generate(respecting options: DocumentationConfiguration) async throws -> String {
        var lines: [String] = []
        if let header, !header.isEmpty {
            lines.append("## \(header)")
        }
        for entry in items {
            let entryString = try await entry.generate(respecting: options)
            lines.append("- \(entryString)")
        }
        return lines.joined(separator: "\n")
    }
}

/// A documentation entry that labels another entry with a known DocC field.
///
/// For example, the `@Doc` macro can wrap a `DocumentationAtom` with a
/// `.returns` field to generate a "- Returns:" section.  Additional fields
/// like `.parameters`, `.throws`, and `.note` are defined here.
@frozen
public struct DocumentationKnownSection<E: DocumentationEntry>: DocumentationEntry, Hashable {
    public var field: Field
    public var value: E
    public init(field: Field, value: E) {
        self.field = field
        self.value = value
    }
    public enum Field: String, CaseIterable, Hashable, Sendable {
        case discussion, parameters, throws, returns
        case precondition, postcondition, requires
        case invariant, complexity, important, warning
        case author, authors, copyright, date, seeAlso
        case since, version
        case attention, bug, experiment, note, remark, toDo
        case unknown
    }
    public func generate(respecting options: DocumentationConfiguration) async throws -> String {
        let valueString = try await value.generate(respecting: options)
        let fieldName = field.rawValue.prefix(1).uppercased() + field.rawValue.dropFirst()
        return "- \(fieldName):\n  \(valueString)"
    }
}

/// A documentation entry representing a fenced code block.
///
/// Instances of `DocumentationCodeBlock` are generated by the `docSwiftCode` macro
/// or by manually constructing them with the desired language and code.  When
/// rendered, the `language` is used as the info string of the fenced code block.
@frozen
public struct DocumentationCodeBlock: DocumentationEntry, Hashable {
    public var language: Language
    public var value: String
    public init(language: Language = .swift, value: String) {
        self.language = language
        self.value = value
    }
    public func generate(respecting options: DocumentationConfiguration) async throws -> String {
        return """
        ```\(language.rawValue)
        \(value)
        ```
        """
    }
    public enum Language: Hashable, Sendable, RawRepresentable {
        case text
        case swift
        case objc
        case json
        case yaml
        case md
        case other(String)
        public init(rawValue: String) {
            switch rawValue.lowercased() {
            case "": self = .text
            case "swift": self = .swift
            case "objc", "objectivec": self = .objc
            case "json": self = .json
            case "yaml": self = .yaml
            case "md", "markdown": self = .md
            default: self = .other(rawValue)
            }
        }
        public var rawValue: String {
            switch self {
            case .text: return ""
            case .swift: return "swift"
            case .objc: return "objc"
            case .json: return "json"
            case .yaml: return "yaml"
            case .md: return "md"
            case .other(let name): return name
            }
        }
    }
}